language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3.5"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install --upgrade pytest
  - pip install --editable .

script:
  - pytest

notifications:
  email: false
